### ISSUE TITLE
Annotated Algorithm Example

### ISSUE THREAD

**Issue by ccorcos** [mweidner037/position-strings#3]
Hey there, I'm just trying to understand how this works by example. I'd appreciate some help understanding some things...

```ts
import { PositionSource } from "position-strings"

const positions: string[] = []

function insert(p: PositionSource, index: number, len: number) {
	for (let i = index; i < index + len; i++) {
		// console.log(positions, positions[i - 1])
		positions.splice(i, 0, p.createBetween(positions[i - 1], positions[i]))
	}
}

const p = new PositionSource({ ID: "A" })
insert(p, 0, 5)
console.log(positions)

// [
// 	"A.B", <- A is the waypoint, B is the lex position.
// 	"A.D",
// 	"A.F",
// 	"A.H",
// 	"A.J"
// ]

insert(p, 2, 5)
console.log(positions)

// [
// 	"A.B",
// 	"A.D",
// 	"A.D0B", <- 0 implies insert on the "left side", and B is the nested lex position.
// 	"A.D0D", <-
// 	"A.D0F", <-
// 	"A.D0H", <-
// 	"A.D0J", <-
// 	"A.F",
// 	"A.H",
// 	"A.J"
// ]

const p2 = new PositionSource({ ID: "B" })
insert(p2, 3, 2)
console.log(positions)

// [
// 	"A.B",
// 	"A.D",
// 	"A.D0B",
// 	"A.D0B,B.B", <- `A.D0B,B` is the waypoint, B is the nested lex position.
// 	"A.D0B,B.D", <-
// 	"A.D0D",
// 	"A.D0F",
// 	"A.D0H",
// 	"A.D0J",
// 	"A.F",
// 	"A.H",
// 	"A.J"
// ]

insert(p, 3, 2)
console.log(positions)

// [
// 	"A.B",
// 	"A.D",
// 	"A.D0B",
// 	"A.D0B,B.A1B", <- what's going on here?
// 	"A.D0B,B.A1D", <-
// 	"A.D0B,B.B",
// 	"A.D0B,B.D",
// 	"A.D0D",
// 	"A.D0F",
// 	"A.D0H",
// 	"A.D0J",
// 	"A.F",
// 	"A.H",
// 	"A.J"
// ]

insert(p2, 6, 2)
console.log(positions)

// [
// 	"A.B",
// 	"A.D",
// 	"A.D0B",
// 	"A.D0B,B.A1B",
// 	"A.D0B,B.A1D",
// 	"A.D0B,B.B",
// 	"A.D0B,B.B0B", <-
// 	"A.D0B,B.B0D", <-
// 	"A.D0B,B.D",
// 	"A.D0D",
// 	"A.D0F",
// 	"A.D0H",
// 	"A.D0J",
// 	"A.F",
// 	"A.H",
// 	"A.J"
// ]

insert(p2, 3, 2)
insert(p, 3, 2)
insert(p2, 3, 2)
console.log(positions)

// [
// 	"A.B",
// 	"A.D",
// 	"A.D0B",
// 	"A.D0B,B.A1A0A1A0B",
// 	"A.D0B,B.A1A0A1A0D",
// 	"A.D0B,B.A1A0A1B",
// 	"A.D0B,B.A1A0A1D",
// 	"A.D0B,B.A1A0B",
// 	"A.D0B,B.A1A0D",
// 	"A.D0B,B.A1B",
// 	"A.D0B,B.A1D",
// 	"A.D0B,B.B",
// 	"A.D0B,B.B0B",
// 	"A.D0B,B.B0D",
// 	"A.D0B,B.D",
// 	"A.D0D",
// 	"A.D0F",
// 	"A.D0H",
// 	"A.D0J",
// 	"A.F",
// 	"A.H",
// 	"A.J"
// ]
```

**Comment by ccorcos** [comment]
If we were to represent this with a data structure instead of  strings, it seems to look like this. However, it's unclear if this nests forever -- I'm only ever seeing one comma per position string... 🤔 

```ts
type LR = 0 | 1

type Index =
	| [{ id: string; pos: string }]
	| [{ id: string; pos: string }, ...Array<{ lr: LR; pos: string }>]
	| [{ id: string; pos: string }, ...Array<{ lr: LR; pos: string }>, { id: string; pos: string }]
	| [{ id: string; pos: string }, ...Array<{ lr: LR; pos: string }>, { id: string; pos: string }, ...Array<{ lr: LR; pos: string }>]
```

**Comment by mweidner037** [comment]
Hi Chet, good questions - I should add examples like these to the [algorithms](https://github.com/mweidner037/position-strings/blob/master/algorithm.md) page.

```ts
insert(p, 2, 5)
console.log(positions)

// [
// 	"A.B",
// 	"A.D",
// 	"A.D0B",
```
The new waypoint is a right child of `A.D`; since `D` is already a right-side signifier (even valueIndex), it stays. Next, `0` is a "short name" that abbreviates the source ID `,A.` - it says "my source ID is the same as the 0th prior 'long name'".

```ts
insert(p, 3, 2)
console.log(positions)

// [
// 	"A.B",
// 	"A.D",
// 	"A.D0B",
// 	"A.D0B,B.A1B", <- what's going on here?
// 	"A.D0B,B.A1D", <-
// 	"A.D0B,B.B",
```
The new waypoint is a left child of `A.D0B,B.B`. We first decrement the final encoded number (`B` = 1) to signify a left child with the same valueIndex (0): `AD0B,B.A`. Next, we have another short name, `1` ("my source ID is the 1th prior 'long name' (0-indexed)"). Finally, `B = 1` for valueIndex 0 with right-side signifier (which is also used for leaves).

> If we were to represent this with a data structure instead of strings, it seems to look like this. However, it's unclear if this nests forever -- I'm only ever seeing one comma per position string... 🤔

There are a couple ways to represent an ordered map (position-string -> value) without storing literally every string:
1. A tree like you suggest - this should be possible with help "parsing" the strings back into a path of (waypoint ID, valueIndex, side, waypoint ID, valueIndex, side, ...).
2. A sequence of "items" (starting position, values), where the values share the same waypoint node with sequential valueIndex - this should be possible with help dividing position-strings into (prefix, valueIndex) pairs.

I am interested in implementing the "helpers" needed here but have not yet had time.

**Comment by ccorcos** [comment]
I see so this is what an "expanded" representation looks like:

`"A.D0B"` → `[{id: "A", pos: "D"}, {id: "A", pos: "B"}]`
`"A.D0B,B.B"` → `[{id: "A", pos: "D"}, {id: "A", pos: "B"},  {id: "B", pos: "B"}]`

And then inserting in between those two would be this item:

`"A.D0B,B.A1B"` → `[{id: "A", pos: "D"}, {id: "A", pos: "B"},  {id: "B", pos: "A"}, {id: "A", pos: "B"}]`

That actually makes a lot of sense once you unpack it. I'm still a little unclear on what you mean by "left child" vs "right child" and the odd vs even valueIndex stuff...

I'm not sure how you feel about this -- I'm sure you've stared at this encoding a lot haha -- but I like this data structure approach not just for readability, but because it also make it easier to experiment with different compression algorithms. Have you thought about any improvements to the compression? I just realized that the compressed representation needs to maintain lexicographic order as well...


Flipping the ids around just to check...

```ts
[
	"B.B",
	"B.D",
	"B.D0B",
	"B.D0D",
	...
]

[
	"B.B",
	"B.D",
	"B.D0B",
	"B.D0B,A.B",
	"B.D0B,A.D",
	...
]

[
	"B.B",
	"B.D",
	"B.D0B",
	"B.D0B,A.A1B",
	"B.D0B,A.A1D",
	"B.D0B,A.B",
	"B.D0B,A.D",
	...
]
```

Interesting... 🤔

**Comment by mweidner037** [comment]
> That actually makes a lot of sense once you unpack it. I'm still a little unclear on what you mean by "left child" vs "right child" and the odd vs even valueIndex stuff...

Each node in the implied tree (e.g. `{id: "A", pos: "D"}`) holds three pieces of info:
- id
- "valueIndex": a number that increases in sequence, for positions created sequentially by the same PositionSource. This is an optimization to help with the common case of left-to-right insertions.
- left/right: a bit that tells you whether the *following* node is a left or right child of this node. A node itself gets the "right" bit, so that (left children) < (node itself) < (right children).

The valueIndex and left/right bit are converted to an integer (`2 * valueIndex + (isRight ? 1: 0)`), then encoded in a special way (base-52 [lex-sequence](https://github.com/mweidner037/lex-sequence/#readme)). E.g. 1 -> `B`, 3 -> `D`, 5 -> `F`.

> I'm not sure how you feel about this -- I'm sure you've stared at this encoding a lot haha -- but I like this data structure approach not just for readability, but because it also make it easier to experiment with different compression algorithms.

I've been working on a second library that takes an approach kind of like that - [list-positions](https://github.com/mweidner037/list-positions). It stores an explicit tree of nodes, and you can ask for a node's "path to the root" as an array, then compress it how you like. (Currently it has its own form of "position strings" - `LexPosition`s - but I might replace these with a non-lexicographic version so that I can experiment with better compression, as you suggest.)

> Have you thought about any improvements to the compression? I just realized that the compressed representation needs to maintain lexicographic order as well...

Yes, the lexicographic order introduces tradeoffs:
- If you want to deduplicate IDs, then this changes the sort order from what you expect - e.g., comparing `0` when the uncompressed version would compare `B`.
- You have to encode the valueIndex/left-right numbers in a funky way.
- To avoid extra delimiter chars ("," / "."), this library does some character-set hacks to delineate boundaries, but then the format is not readable.

My current plan is:
- In position-strings, make the strings as short as possible while still being lexicographically sortable, and sacrifice everything else (readability, storage efficiency, custom compression).
- In list-positions, do everything else as well as possible, and forget about lexicographic sorting (or offer it only as a non-optimized escape hatch).

But I am open to suggestions.

**Comment by ccorcos** [comment]
Hmm. I'm a little unclear how the "left vs right" bit  actually represents a tree structure though. The way I understand it, you could have given yourself more space in between indexes by incrementing every `nth` (5th or 10th) value intead of 2. I'm still trying to transfer my understanding of [fractional indexing](https://observablehq.com/@dgreensp/implementing-fractional-indexing) onto this project...

I'm curious about your motivations for list-positions. The lexicographic sorting is crucially important to me so I can index lists in a database with a btree. If its not lexicographically ordered, then its not exactly useful for me. I suppose something like ProseMirror might need something like that, but I'm sure they already have something that works.

**Comment by mweidner037** [comment]
> The way I understand it, you could have given yourself more space in between indexes by incrementing every nth (5th or 10th) value intead of 2. 

Yes, this is the main insight of the [LSeq](https://hal.archives-ouvertes.fr/file/index/docid/921633/filename/fp025-nedelec.pdf) CRDT, which is somewhat similar (a tree of `(creatorID, arbitrary integer)` pairs, with siblings ordered by the integer and then the creatorID). I've shied away from ideas like this because they add implementation complexity and lead to interleaving.

> I suppose something like ProseMirror might need something like that, but I'm sure they already have something that works.

ProseMirror does have a nice internal representation of the text, but it doesn't assign immutable "positions" to characters that you can refer to in a collaborative setting. At best, you can refer to a character by its index in a specific state, then *transform* indices between different states - how PM's internal [OT](https://en.wikipedia.org/wiki/Operational_transformation) algorithm works. But I am interested in CRDT solutions that work in decentralized settings.

**Comment by ccorcos** [comment]
I'm not sure why the lseq approach needs to lead to interleaving...

**Comment by mweidner037** [comment]
> I'm not sure why the lseq approach needs to lead to interleaving...

Hmm, maybe it is okay in the situation you're describing.

So in the original LSeq/Logoot CRDT, each tree node is a pair `(arbitrary integer, creator ID)`, with siblings sorted first by integer and then by ID. So Alice and Bob could concurrently insert sequences like:
```
Alice: [(1, "alice")], [(2, "alice")], [(3, "alice")], ...
Bob:   [(1, "bob")], [(2, "bob")], [(3, "bob")], ...
```
which become interleaved:
```
[(1, "alice")], [(1, "bob")], [(2, "alice")], [(2, "bob")], [(3, "alice")], [(3, "bob")]...
```
But if you flip it around - sort siblings by creator ID, then the arbitrary integer - interleaving goes away.

Applied to position-strings, you could decree that each node has a label `(creator ID, valueIndex, fractional index)`, with siblings sorted first by creator ID, etc. This looks non-interleaving and would incorporate both optimizations (valueIndex for sequential insertions, and fractional index for arbitrary insertions by a single user).

If you want to make something like this for your use case, I'm happy to help. Though for position-strings itself, I would prefer to keep just the valueIndex optimization, for the sake of simplicity.

**Comment by ccorcos** [comment]
Yeah sounds good. I might take a stab at this eventually. Just wanted to get a grasp on things first. I'll keep you posted :)
